export const orderConstants = {
    ADD_TO_BASKET_REQUEST: 'ADD_TO_BASKET_REQUEST',
    ADD_TO_BASKET_SUCCESS: 'ADD_TO_BASKET_SUCCESS',
    ADD_TO_BASKET_FAILURE: 'ADD_TO_BASKET_FAILURE',
    GET_BASKET_REQUEST: 'GET_BASKET_REQUEST',
    GET_BASKET_SUCCESS: 'GET_BASKET_SUCCESS',
    GET_BASKET_FAILURE: 'GET_BASKET_FAILURE'
};