export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_INVALID_IDENTIFIER: 'LOGIN_INVALID_IDENTIFIER',
    LOGIN_INVALID_PASSWORD: 'LOGIN_INVALID_PASSWORD',
    LOGOUT: 'USERS_LOGOUT',
};