export const registerConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    PHONE_ALREADY_USED: 'PHONE_ALREADY_USED'
};